export const ADD_MOVIE = 'ADD_MOVIE'
export const SET_MOVIES = 'SET_MOVIES'
export const REMOVE_MOVIE = 'REMOVE_MOVIE'
export const CHANGE_PREVIEW = 'CHANGE_PREVIEW'
export const ADD_RECENT = 'ADD_RECENT'
export const SET_RECENT = 'SET_RECENT'
